name: test

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up python3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Install dependencies
      run: pipenv install -d
    - name: Run tests
      run: pipenv run pytest
